version: '3.5'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./
      dockerfile: backend/Dockerfile
    volumes:
      - C:/Users/Miguel/Desktop/detector_grpc/Images:/home/images
    command: [python, backend.py]

  ui:
    container_name: interface
    image: interface:1.0.0
    build:
      context: ./
      dockerfile: interface/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - C:/Users/Miguel/Desktop/detector_grpc/Images:/home/images
    environment:
      - DISPLAY=host.docker.internal:0
    command: [python, interface.py]